// app/layout.tsx
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import ClientLayout from "@/components/layout/ClientLayout";

const sfProDisplay = localFont({
  src: [
    {
    path: './fonts/SFPRODISPLAYREGULAR.woff2',
    weight: '400',
    style: 'normal',
    },

  {
    path: './fonts/SFPRODISPLAYMEDIUM.woff2',
    weight: '500',
    style: 'normal',
  },

  {
    path: './fonts/SFPRODISPLAYBOLD.woff2',
    weight: '700',
    style: 'normal',
  }
  ],
  variable: '--sf-pro-display'
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-poppins'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={`${sfProDisplay.variable} ${poppins.variable} bg-[#F4F4F4] text-text font-sans sfPro`}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}